title: Maximilian Köhl
email: mail@koehlma.de
author: Maximilian Köhl

description: >
 Hello! I am Maximilian Köhl, an OpenSource enthusiast and computer science student.

baseurl: ""
url: "https://www.koehlma.de"
permalink: /:year/:month/:title.html

twitter_username: koehlma
github_username: koehlma

markdown: kramdown
